language: python
python:
- 3.8.12
services:
- postgresql
install:
- psql -c 'create database django_db owner postgres;' -U postgres
- pip install -r requirements.txt
script:
- python manage.py migrate
deploy:
  provider: heroku
  deploy:
  api_key:
    secure: e3IE8uSkCPNkCROQLbdAy3BpeRzHjzibhkZc7fid/ZADCFi+LDHOYaHu0D6J8gj0i5n4tSa6ldlZ3ebSIq8rlMsouaAISCDV0vqo1NcF9FW+OnPCWvkUFxAHW/ldCttV0yLgtw8EV66Vv7M9T3LTEymzNyRU5vlhU5h7Q3l6/lOdHISh70YnlJlRnz3hJWDqCxXd7EYlGEo/EI3Vai5T3/DPxYBNYsUB7z9Ebtm2VBjqDwEjEqqLKQN6vdhZR5myu8//RcQNVYHSAGZ6OqFxNf05LrVisuHMbo/hpHDTrZS/kF/S3TYCLOL9PGN7cU+HSL+JPzoeabRfBiqps6P2DFxHOa1W10bHsTVZaDXLcOjcLYnwtItmYHbTv43csHd4U/CeZzslF4NpEm2NRgssFzSd6r+do1ZELjTxMeYtwkAj8GIRJIc3cblxnj1YytmgcHEputZw1MqAy6KIO39ElM5+FGk9nAc7QHN5GWODIxrgxmgBJj8jbQnnjuKlR5PZzZ73mwbuItotYcYv+Px9D58wO6GF6PaQGHdOan+xfkrX7a9OvIctu8KN6dsnFPMPTCIgvZLVg7lCnBIkTguMCvbDMUu3e5WWiaH/fFfS13EYFBDfoCW/SILbDnd0MLkc9cb/Jpl/k5KL5Or2Uk4bGShnWoSefjhUgilPw0ev+xk=
  app: nikitin