# Generated by Django 4.0.1 on 2022-01-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_komplekt_gigabyte_alter_komplekt_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komplekt',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='komplekt',
            old_name='gigabyte',
            new_name='year',
        ),
    ]
