# Generated by Django 4.0.1 on 2022-01-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_rename_title_komplekt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='komplekt',
            name='price',
            field=models.CharField(default='', max_length=200),
        ),
    ]
