# Generated by Django 4.0.1 on 2022-01-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
