# Generated by Django 4.0.1 on 2022-01-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_alter_music_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='description',
            new_name='descriptions',
        ),
    ]
