# Generated by Django 4.0.1 on 2022-01-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_rename_description_music_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
